name: CI on Branched and PRs

on:
  workflow_dispatch:
    branches: 
      - '!master'
     
  push:
    branches: 
      - '!master'
     
  pull_request:
    branches: 
      - master
    paths: 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.4
      with:
        versionSpec: "5.2.x"
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "2.0.x"
    - name: Install dependencies
      run: dotnet restore src/Easify.Azure.sln
    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.4
    - name: Display the version
      run: |
        echo "Version: ${{ steps.gitversion.outputs.semver }}"
    - name: Build & Test with dotnet
      run: |
        dotnet build src/Easify.Azure.sln --configuration Release --no-restore -p:version=${{ steps.gitversion.outputs.semver }}
    - name: Unit & integration test
      run: |
        dotnet test src/Easify.Azure.sln --configuration Release --no-restore -p:version=${{ steps.gitversion.outputs.semver }}    
    - uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: "**/*.nupkg"
    - name: Configure github as Package Repository
      run: dotnet nuget add source https://nuget.pkg.github.com/icgam/index.json -n "github" 
    - name: Publish the package to GitHub Packages
      run: dotnet nuget push "**/*.nupkg" -s "github" -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate

